import { useEffect, useState } from 'react'
import type { FormEvent } from 'react'
import { Link, useParams } from 'react-router-dom'
import { ApiError, apiRequest } from '../lib/api'
import type { InventorySku, Page } from '../types/operations'

type Movement = { id: string; movement_type: string; on_hand_delta: number; resulting_on_hand: number; resulting_reserved: number; reason: string; created_at: string }

function variantLabel(variant: InventorySku['variant']): string {
  return variant?.option_values.map(({ group, value }) => group ? `${group}: ${value}` : value).join(' / ') ?? ''
}

export function InventoryDetailPage() {
  const { skuId } = useParams()
  const [sku, setSku] = useState<InventorySku | null>(null)
  const [movements, setMovements] = useState<Movement[]>([])
  const [type, setType] = useState('restock'); const [quantity, setQuantity] = useState('1'); const [reason, setReason] = useState(''); const [threshold, setThreshold] = useState(''); const [error, setError] = useState(''); const [reload, setReload] = useState(0)
  useEffect(() => { if (!skuId) return; Promise.all([apiRequest<{ data: InventorySku }>(`/api/v1/seller/inventory/${skuId}`), apiRequest<Page<Movement>>(`/api/v1/seller/inventory/${skuId}/movements`)]).then(([item, history]) => { setSku(item.data); setThreshold(item.data.alert_threshold?.toString() ?? ''); setMovements(history.data) }) }, [skuId, reload])
  async function adjust(e: FormEvent) { e.preventDefault(); setError(''); try { await apiRequest(`/api/v1/seller/inventory/${skuId}/adjustments`, { method: 'POST', body: JSON.stringify({ movement_type: type, quantity: Number(quantity), reason, idempotency_key: crypto.randomUUID() }) }); setReason(''); setReload((v) => v + 1) } catch (e) { setError(e instanceof ApiError ? Object.values(e.errors)[0]?.[0] ?? e.message : 'Adjustment failed.') } }
  async function saveThreshold() { await apiRequest(`/api/v1/seller/inventory/${skuId}/threshold`, { method: 'PATCH', body: JSON.stringify({ alert_threshold: threshold === '' ? null : Number(threshold) }) }); setReload((v) => v + 1) }
  if (!sku) return <p className="p-8 text-sm text-zinc-500">Loading inventory…</p>
  return <div className="mx-auto max-w-5xl px-4 py-7 sm:px-6 lg:px-8"><Link className="text-sm text-zinc-500" to="/inventory">← Inventory</Link><div className="mt-3 border-b border-zinc-200 pb-5 dark:border-white/10"><h2 className="text-2xl font-semibold">{sku.product.name}</h2>{sku.variant ? <p className="mt-1 text-sm text-zinc-600 dark:text-zinc-300">{variantLabel(sku.variant)}</p> : null}<p className="mt-1 font-mono text-sm text-zinc-500">{sku.code}</p></div>
    <div className="mt-6 grid gap-6 lg:grid-cols-[1fr_22rem]"><section className="rounded-lg border border-zinc-200 bg-white dark:border-white/10 dark:bg-[#18181b]"><div className="grid grid-cols-3 border-b border-zinc-200 dark:border-white/10">{[['On hand', sku.on_hand], ['Reserved', sku.reserved], ['Available', sku.available]].map(([label, value]) => <div className="p-4" key={label}><p className="text-xs text-zinc-500">{label}</p><p className="mt-1 text-xl font-semibold tabular-nums">{value}</p></div>)}</div><div className="p-5"><h3 className="font-semibold">Movement history</h3><div className="mt-3 divide-y divide-zinc-200 dark:divide-white/10">{movements.length ? movements.map((m) => <div className="flex justify-between gap-4 py-3 text-sm" key={m.id}><div><p className="font-medium capitalize">{m.movement_type.replace('_', ' ')}</p><p className="mt-1 text-xs text-zinc-500">{m.reason}</p></div><div className="text-right"><p className={m.on_hand_delta >= 0 ? 'text-emerald-700 dark:text-emerald-400' : 'text-red-700 dark:text-red-400'}>{m.on_hand_delta > 0 ? '+' : ''}{m.on_hand_delta}</p><p className="mt-1 text-xs text-zinc-500">{new Date(m.created_at).toLocaleString()}</p></div></div>) : <p className="py-4 text-sm text-zinc-500">No movements yet.</p>}</div></div></section>
      <aside className="space-y-5"><form className="rounded-lg border border-zinc-200 bg-white p-5 dark:border-white/10 dark:bg-[#18181b]" onSubmit={adjust}><h3 className="font-semibold">Adjust stock</h3>{error ? <p className="mt-3 text-sm text-red-700">{error}</p> : null}<label className="mt-4 block text-sm">Type<select className="mt-1 h-10 w-full rounded-lg border border-zinc-300 bg-white px-3 dark:border-white/15 dark:bg-[#18181b]" onChange={(e) => setType(e.target.value)} value={type}><option value="restock">Restock</option><option value="manual_increase">Manual increase</option><option value="manual_decrease">Manual decrease</option><option value="return_in">Return</option></select></label><label className="mt-4 block text-sm">Quantity<input className="mt-1 h-10 w-full rounded-lg border border-zinc-300 bg-white px-3 dark:border-white/15 dark:bg-[#18181b]" min="1" onChange={(e) => setQuantity(e.target.value)} required type="number" value={quantity} /></label><label className="mt-4 block text-sm">Reason<textarea className="mt-1 min-h-20 w-full rounded-lg border border-zinc-300 bg-white p-3 dark:border-white/15 dark:bg-[#18181b]" onChange={(e) => setReason(e.target.value)} required value={reason} /></label><button className="mt-4 h-10 w-full rounded-lg bg-[#4C1268] text-sm font-medium text-white">Record adjustment</button></form>
      <div className="rounded-lg border border-zinc-200 bg-white p-5 dark:border-white/10 dark:bg-[#18181b]"><h3 className="font-semibold">Low-stock alert</h3><label className="mt-3 block text-sm">Threshold<input className="mt-1 h-10 w-full rounded-lg border border-zinc-300 bg-white px-3 dark:border-white/15 dark:bg-[#18181b]" min="0" onChange={(e) => setThreshold(e.target.value)} placeholder="Disabled" type="number" value={threshold} /></label><button className="mt-3 h-10 w-full rounded-lg border border-zinc-300 text-sm font-medium dark:border-white/15" onClick={() => void saveThreshold()}>Save threshold</button></div></aside></div>
  </div>
}
