import { useCallback, useEffect, useState } from 'react'
import { FaDownload, FaEye, FaPrint } from 'react-icons/fa6'
import { Link } from 'react-router-dom'
import { useAuth } from '../auth/useAuth'
import { OrderButton, OrderError, orderLink, orderPanel } from '../components/orders/OrderUi'
import { ApiError, apiPdfRequest } from '../lib/api'
import { createPickupRequest } from '../lib/sellerOrderActions'
import { getSellerLogisticsOptions, type LogisticsOption } from '../lib/sellerLogisticsOptions'
import { useOrderAccessError, useSellerOrders } from '../lib/useSellerOrders'
import { orderDate, type SellerOrder, type SellerOrderPage } from '../types/orders'

async function handlePdf(path: string, mode: 'preview' | 'download' | 'print', filename: string) {
  const popup = mode === 'download' ? null : window.open('', '_blank')
  try {
    const blob = await apiPdfRequest(path)
    const objectUrl = URL.createObjectURL(blob)
    if (mode === 'download') { const link = document.createElement('a'); link.href = objectUrl; link.download = filename; link.click(); window.setTimeout(() => URL.revokeObjectURL(objectUrl), 60_000); return }
    if (!popup) throw new Error('Pop-up blocked')
    popup.location.href = objectUrl
    if (mode === 'print') popup.addEventListener('load', () => popup.print(), { once: true })
    window.setTimeout(() => URL.revokeObjectURL(objectUrl), 300_000)
  } catch (error) { popup?.close(); throw error }
}

export function OrderPickupPage() {
  const { seller } = useAuth()
  const accessError = useOrderAccessError()
  const processing = useSellerOrders<SellerOrderPage>('/api/v1/seller/orders?status=seller_processing&sort=oldest&per_page=50')
  const pending = useSellerOrders<SellerOrderPage>('/api/v1/seller/orders?status=ready_for_pickup&sort=activity_desc&per_page=50')
  const [providers, setProviders] = useState<LogisticsOption[]>([])
  const [providerLoading, setProviderLoading] = useState(true)
  const [providerId, setProviderId] = useState('')
  const [selected, setSelected] = useState<string[]>([])
  const [submitting, setSubmitting] = useState(false)
  const [pdfBusy, setPdfBusy] = useState('')
  const [error, setError] = useState('')
  const [notice, setNotice] = useState('')
  useEffect(() => { document.title = 'Order pickup | Aisley Seller' }, [])
  const loadProviders = useCallback(async (force = false) => { if (!seller) { setProviderLoading(false); return } setProviderLoading(true); try { const result = await getSellerLogisticsOptions(seller.id, force); setProviders(result.data); setProviderId((current) => result.data.some((option) => option.id === current) ? current : result.data.find((option) => option.recommended)?.id || ''); setError('') } catch (reason) { if (!accessError(reason)) setError(reason instanceof ApiError ? reason.message : 'Logistics providers could not be loaded.') } finally { setProviderLoading(false) } }, [accessError, seller])
  useEffect(() => { void loadProviders() }, [loadProviders])
  const eligible = processing.data?.data ?? []
  const pickupGroups = Object.values((pending.data?.data ?? []).reduce<Record<string, SellerOrder[]>>((groups, order) => { const key = order.pickup?.request_id ?? order.id; (groups[key] ??= []).push(order); return groups }, {}))
  function toggle(id: string) { setSelected((current) => current.includes(id) ? current.filter((value) => value !== id) : [...current, id]) }
  async function submit() { if (!seller || selected.length === 0 || !providerId || submitting) return; setSubmitting(true); setError(''); setNotice(''); try { const response = await createPickupRequest(seller.id, selected, providerId)(); setSelected([]); setNotice(`${response.data.order_ids.length} ${response.data.order_ids.length === 1 ? 'Order is' : 'Orders are'} ready for pickup. Print and attach each waybill before handoff.`); processing.refresh(); pending.refresh() } catch (reason) { if (!accessError(reason)) setError(reason instanceof ApiError ? reason.message : 'The pickup request could not be submitted. Refresh and try again.') } finally { setSubmitting(false) } }
  async function waybill(path: string, key: string, mode: 'preview' | 'download' | 'print', filename: string) { setPdfBusy(`${key}:${mode}`); setError(''); try { await handlePdf(`${path}${path.includes('?') ? '&' : '?'}disposition=inline`, mode, filename) } catch (reason) { setError(reason instanceof ApiError ? reason.message : 'The waybill could not be opened. Allow pop-ups for preview or print and try again.') } finally { setPdfBusy('') } }
  return <div className="mx-auto max-w-6xl px-4 py-7 sm:px-6 lg:px-8">
    <div className="flex flex-wrap items-start justify-between gap-4 border-b border-zinc-200 pb-5 dark:border-white/10"><div><h2 className="text-2xl font-semibold">Order pickup</h2><p className="mt-1 text-sm text-zinc-600 dark:text-zinc-400">Prepare parcels, choose a Logistics provider, and print the shared waybills.</p></div><OrderButton isLoading={processing.loading || pending.loading || providerLoading} loadingLabel="Refreshing" onClick={() => { processing.refresh(); pending.refresh(); void loadProviders(true) }}>Refresh</OrderButton></div>
    <section className={`${orderPanel} mt-5 p-5`} aria-labelledby="packing-steps"><h3 className="font-semibold" id="packing-steps">Before requesting pickup</h3><ol className="mt-3 grid gap-2 text-sm text-zinc-700 dark:text-zinc-300 sm:grid-cols-2"><li><strong>1.</strong> Confirm the items, then pack and seal each Order separately.</li><li><strong>2.</strong> Select one Logistics provider for the request.</li><li><strong>3.</strong> Request pickup, then print each generated waybill.</li><li><strong>4.</strong> Attach it flat outside the parcel with the QR and reference uncovered.</li></ol><p className="mt-3 border-t border-zinc-200 pt-3 text-xs text-zinc-500 dark:border-white/10">Do not place the waybill across a seam or fold it. Avoid tape glare over the QR. Reprint damaged or unreadable labels.</p></section>
    {error && <OrderError message={error} retry={() => { processing.refresh(); pending.refresh(); void loadProviders(true) }} />}{notice && <p className="my-4 rounded-lg border border-green-200 bg-green-50 p-4 text-sm text-green-800 dark:border-green-400/20 dark:bg-green-400/10 dark:text-green-200" role="status">{notice}</p>}
    <section className={`${orderPanel} mt-5`} aria-labelledby="ready-to-submit"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-zinc-200 p-5 dark:border-white/10"><div><h3 className="font-semibold" id="ready-to-submit">Prepared orders</h3><p className="mt-1 text-sm text-zinc-500">{eligible.length} available · {selected.length} selected</p></div><OrderButton variant="secondary" disabled={!selected.length || !providerId || providers.length === 0} isLoading={submitting} loadingLabel="Requesting pickup" onClick={() => void submit()}>Request pickup</OrderButton></div>
      <div className="border-b border-zinc-200 p-5 dark:border-white/10"><label className="block text-sm font-medium" htmlFor="logistics-provider">Logistics provider</label><select className="mt-2 min-h-11 w-full rounded-lg border border-zinc-300 bg-white px-3 text-sm outline-none focus:border-[#4C1268] focus:ring-2 focus:ring-[#4C1268]/15 dark:border-white/15 dark:bg-[#111113]" disabled={providerLoading || providers.length === 0} id="logistics-provider" onChange={(event) => setProviderId(event.target.value)} value={providerId}><option value="">Select a provider</option>{providers.map((option) => <option key={option.id} value={option.id}>{option.business_name} — {option.hub.area.city_municipality}, {option.hub.area.province}{option.distance_km === null ? ' · distance unavailable' : ` · ${option.distance_km.toFixed(1)} km`}{option.recommended ? ' · Recommended' : ''}</option>)}</select>{providers.length === 0 && !providerLoading ? <p className="mt-2 text-sm text-amber-700 dark:text-amber-300">No eligible provider is available. Retry after a Logistics organization has an approved active Courier.</p> : providerId ? <ProviderNote option={providers.find((option) => option.id === providerId)} /> : <p className="mt-2 text-xs text-zinc-500">Confirm a provider before submitting. Distances appear only when calculated by Geoapify Route Matrix.</p>}<p className="mt-2 text-[11px] text-zinc-500">Distance data © Geoapify · OpenStreetMap contributors</p></div>
      {processing.error ? <div className="px-5"><OrderError message={processing.error} retry={processing.refresh} /></div> : eligible.length === 0 ? <p className="p-5 text-sm text-zinc-600 dark:text-zinc-400">Approved Orders appear here while they are being prepared.</p> : <ul className="divide-y divide-zinc-200 dark:divide-white/10">{eligible.map((order) => <SelectableOrder checked={selected.includes(order.id)} key={order.id} order={order} toggle={toggle} />)}</ul>}
    </section>
    <section className={`${orderPanel} mt-5`} aria-labelledby="pending-pickup"><div className="border-b border-zinc-200 p-5 dark:border-white/10"><h3 className="font-semibold" id="pending-pickup">Pickup requests</h3></div>{pending.error ? <div className="px-5"><OrderError message={pending.error} retry={pending.refresh} /></div> : pickupGroups.length === 0 ? <p className="p-5 text-sm text-zinc-600 dark:text-zinc-400">No pickup requests are pending.</p> : <div className="divide-y divide-zinc-200 dark:divide-white/10">{pickupGroups.map((orders) => { const requestId = orders[0].pickup?.request_id ?? orders[0].id; return <section className="p-5" key={requestId}><div className="flex flex-wrap justify-between gap-3 text-sm"><div><h4 className="font-medium">Pickup request · {orders.length} {orders.length === 1 ? 'Order' : 'Orders'}</h4><p className="mt-1 text-zinc-500">Submitted {orderDate(orders[0].latest_activity_at)}</p></div><div className="flex flex-wrap items-start gap-2">{orders.length <= 30 ? <OrderButton isLoading={pdfBusy === `${requestId}:print`} onClick={() => void waybill(`/api/v1/seller/pickup-requests/${requestId}/waybills.pdf`, requestId, 'print', `pickup-waybills-${requestId}.pdf`)}><FaPrint />Print all</OrderButton> : <span className="max-w-52 text-xs text-zinc-500">Bulk print supports 30 labels. Print these waybills individually.</span>}</div></div><ul className="mt-3 divide-y divide-zinc-200 border-y border-zinc-200 dark:divide-white/10 dark:border-white/10">{orders.map((order) => <li className="flex flex-wrap items-center justify-between gap-3 py-3 text-sm" key={order.id}><div><Link className={orderLink} to={`/orders/${order.id}`}>{order.reference}</Link>{order.waybill ? <p className="mt-1 text-xs text-zinc-500">{order.waybill.reference}</p> : null}{order.pickup?.schedule ? <p className="mt-1 text-xs font-medium text-[#4C1268] dark:text-purple-300">Pickup {pickupWindow(order.pickup.schedule.starts_at, order.pickup.schedule.ends_at)} PHT · {order.pickup.schedule.reference}</p> : <p className="mt-1 text-xs text-zinc-500">Waiting for Logistics to schedule pickup</p>}</div>{order.waybill ? <div className="flex gap-2"><OrderButton isLoading={pdfBusy === `${order.id}:preview`} onClick={() => void waybill(order.waybill!.pdf_url, order.id, 'preview', `waybill-${order.waybill!.reference}.pdf`)}><FaEye />Preview</OrderButton><OrderButton aria-label={`Download ${order.waybill.reference}`} isLoading={pdfBusy === `${order.id}:download`} onClick={() => void waybill(order.waybill!.pdf_url, order.id, 'download', `waybill-${order.waybill!.reference}.pdf`)}><FaDownload /></OrderButton><OrderButton aria-label={`Print ${order.waybill.reference}`} isLoading={pdfBusy === `${order.id}:print`} onClick={() => void waybill(order.waybill!.pdf_url, order.id, 'print', `waybill-${order.waybill!.reference}.pdf`)}><FaPrint /></OrderButton></div> : <span className="text-xs text-zinc-500">Waybill unavailable</span>}</li>)}</ul></section> })}</div>}</section>
  </div>
}

function ProviderNote({ option }: { option?: LogisticsOption }) { if (!option) return null; const reason = option.recommendation_reason === 'same_city' ? 'Same city as your pickup address' : option.recommendation_reason === 'same_province' ? 'Same province as your pickup address' : option.recommendation_reason === 'nearest_by_road' ? 'Nearest available road distance' : 'Eligible for this pickup'; return <p className="mt-2 text-xs text-zinc-500">{reason}{option.distance_km === null ? ' · Distance unavailable' : ` · ${option.distance_km.toFixed(1)} km by road`}{option.recommended ? ' · Recommended' : ''}</p> }
function pickupWindow(startsAt: string, endsAt: string) { return `${new Intl.DateTimeFormat('en-PH', { dateStyle: 'medium', timeStyle: 'short', timeZone: 'Asia/Manila' }).format(new Date(startsAt))}–${new Intl.DateTimeFormat('en-PH', { timeStyle: 'short', timeZone: 'Asia/Manila' }).format(new Date(endsAt))}` }
function SelectableOrder({ order, checked, toggle }: { order: SellerOrder; checked: boolean; toggle: (id: string) => void }) { return <li className="flex gap-3 p-5"><input className="mt-1 size-4 accent-[#4C1268]" type="checkbox" id={`pickup-${order.id}`} checked={checked} onChange={() => toggle(order.id)} /><label className="min-w-0 flex-1" htmlFor={`pickup-${order.id}`}><span className="font-medium">{order.reference}</span><span className="mt-1 block truncate text-sm text-zinc-600 dark:text-zinc-400">{order.items.map((item) => `${item.quantity} × ${item.product_name}`).join(', ')}</span></label><Link className={`${orderLink} text-sm`} to={`/orders/${order.id}/prepare`}>Review</Link></li> }
