<?php

namespace App\Http\Controllers\Seller;

use App\Http\Controllers\Controller;
use App\Http\Requests\Seller\AcceptSellerOrderRequest;
use App\Http\Requests\Seller\ListSellerOrdersRequest;
use App\Http\Requests\Seller\RejectSellerOrderRequest;
use App\Http\Requests\Seller\RequestSellerPickupRequest;
use App\Http\Resources\Seller\SellerOrderNotificationResource;
use App\Http\Resources\Seller\SellerOrderResource;
use App\Models\User;
use App\Services\Seller\AcceptSellerOrder;
use App\Services\Seller\RejectSellerOrder;
use App\Services\Seller\RequestSellerPickup;
use App\Services\Seller\SellerOrderService;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Resources\Json\AnonymousResourceCollection;
use Illuminate\Notifications\DatabaseNotification;

class OrderController extends Controller
{
    public function index(ListSellerOrdersRequest $request, SellerOrderService $orders): AnonymousResourceCollection
    {
        /** @var User $seller */
        $seller = $request->user();

        return SellerOrderResource::collection($orders->list($seller, $request->validated()))
            ->additional(['status_counts' => $orders->statusCounts($seller)]);
    }

    public function show(Request $request, string $order, SellerOrderService $orders): SellerOrderResource
    {
        /** @var User $seller */
        $seller = $request->user();

        return new SellerOrderResource($orders->detail($seller, $order));
    }

    public function accept(AcceptSellerOrderRequest $request, string $order, AcceptSellerOrder $accept): SellerOrderResource
    {
        /** @var User $seller */
        $seller = $request->user();

        return new SellerOrderResource($accept->handle($seller, $order, $request->idempotencyKey()));
    }

    public function reject(RejectSellerOrderRequest $request, string $order, RejectSellerOrder $reject): SellerOrderResource
    {
        /** @var User $seller */
        $seller = $request->user();

        return new SellerOrderResource($reject->handle($seller, $order, $request->idempotencyKey(), $request->validated('reason')));
    }

    public function requestPickup(RequestSellerPickupRequest $request, RequestSellerPickup $pickup): JsonResponse
    {
        /** @var User $seller */
        $seller = $request->user();
        $record = $pickup->handle($seller, $request->validated('order_ids'), $request->idempotencyKey());

        return response()->json(['data' => [
            'id' => $record->id,
            'status' => $record->status,
            'pickup_date' => $record->pickup_date?->toDateString(),
            'logistics_organization_id' => $record->logistics_organization_id,
            'order_ids' => $record->orders->pluck('order_id')->values(),
        ]]);
    }

    public function markNotificationRead(Request $request, string $notification): JsonResponse
    {
        /** @var User $seller */
        $seller = $request->user();
        /** @var DatabaseNotification $record */
        $record = $seller->notifications()
            ->where('type', 'seller-order.actionable')
            ->whereKey($notification)
            ->firstOrFail();
        if ($record->read_at === null) {
            $record->markAsRead();
        }

        return response()->json([
            'message' => 'Notification marked as read.',
            'data' => new SellerOrderNotificationResource($record->refresh()),
        ]);
    }

    public function waybill(Request $request, string $order, SellerOrderService $orders): JsonResponse
    {
        /** @var User $seller */
        $seller = $request->user();
        $orders->detail($seller, $order);

        return response()->json([
            'code' => 'WAYBILL_NOT_AVAILABLE',
            'message' => 'A waybill has not been generated by Logistics.',
        ], 404);
    }
}
