import { Navigate, Route, Routes } from 'react-router-dom'
import { ProtectedRoute } from './components/ProtectedRoute'
import { LogisticsLayout } from './layouts/LogisticsLayout'
import { DashboardPage } from './pages/DashboardPage'
import { ForgotPasswordPage } from './pages/ForgotPasswordPage'
import { LoginPage } from './pages/LoginPage'
import { RegisterPage } from './pages/RegisterPage'
import { ResetPasswordPage } from './pages/ResetPasswordPage'
import { PickupsPage } from './pages/PickupsPage'
import { PickupDetailPage } from './pages/PickupDetailPage'
import { AccountPage } from './pages/AccountPage'
import { PolicyConsentPage } from './pages/PolicyConsentPage'
import { CourierApplicationsPage } from './pages/CourierApplicationsPage'
import { CourierApplicationDetailPage } from './pages/CourierApplicationDetailPage'
import { CourierVehiclePage } from './pages/CourierVehiclePage'
import { CourierVehiclesPage } from './pages/CourierVehiclesPage'
import { FulfillmentOperationsPage } from './pages/FulfillmentOperationsPage'
import { NotificationsPage } from './pages/NotificationsPage'
import { ReceiveAtHubPage } from './pages/ReceiveAtHubPage'
import { DispatchPage } from './pages/DispatchPage'
import { LinehaulPage } from './pages/LinehaulPage'
import { SortingPage } from './pages/SortingPage'
import { SortPlanPage } from './pages/SortPlanPage'
import { NotFoundPage } from './pages/NotFoundPage'
import { FleetPage } from './pages/FleetPage'
import { InboundLinehaulPage } from './pages/InboundLinehaulPage'
import { LinehaulDispatchPage } from './pages/LinehaulDispatchPage'
export default function App() { return <Routes><Route element={<Navigate replace to="/dashboard" />} path="/" /><Route element={<LoginPage />} path="/login" /><Route element={<RegisterPage />} path="/register" /><Route element={<ForgotPasswordPage />} path="/forgot-password" /><Route element={<ResetPasswordPage />} path="/reset-password" /><Route element={<ProtectedRoute />}><Route element={<LogisticsLayout />}><Route element={<DashboardPage />} path="/dashboard" /><Route element={<FulfillmentOperationsPage />} path="/operations" /><Route element={<ReceiveAtHubPage />} path="/receive-at-hub" /><Route element={<LinehaulPage />} path="/linehaul" /><Route element={<LinehaulDispatchPage />} path="/linehaul-dispatch" /><Route element={<InboundLinehaulPage />} path="/inbound-linehaul" /><Route element={<SortingPage />} path="/sorting" /><Route element={<SortPlanPage />} path="/sort-plan" /><Route element={<DispatchPage />} path="/dispatch" /><Route element={<PickupsPage />} path="/pickups" /><Route element={<PickupDetailPage />} path="/pickups/:pickupId" /><Route element={<CourierApplicationsPage />} path="/courier-applications" /><Route element={<CourierApplicationDetailPage />} path="/courier-applications/:affiliationId" /><Route element={<FleetPage />} path="/fleet" /><Route element={<CourierVehiclesPage />} path="/vehicles" /><Route element={<CourierVehiclePage />} path="/couriers/:courierId/vehicle" /><Route element={<NotificationsPage />} path="/notifications" /><Route element={<NotificationsPage />} path="/notifications/:notificationId" /><Route element={<AccountPage />} path="/account" /><Route element={<PolicyConsentPage />} path="/policy-consent" /><Route element={<NotFoundPage />} path="*" /></Route></Route><Route element={<Navigate replace to="/dashboard" />} path="*" /></Routes> }
