import { Navigate, Route, Routes } from 'react-router-dom'
import { ProtectedRoute } from './components/ProtectedRoute'
import { LogisticsLayout } from './layouts/LogisticsLayout'
import { DashboardPage } from './pages/DashboardPage'
import { ForgotPasswordPage } from './pages/ForgotPasswordPage'
import { LoginPage } from './pages/LoginPage'
import { RegisterPage } from './pages/RegisterPage'
import { ResetPasswordPage } from './pages/ResetPasswordPage'
import { PickupsPage } from './pages/PickupsPage'
import { PickupDetailPage } from './pages/PickupDetailPage'
import { AccountPage } from './pages/AccountPage'
import { PolicyConsentPage } from './pages/PolicyConsentPage'
import { CourierApplicationsPage } from './pages/CourierApplicationsPage'
import { CourierApplicationDetailPage } from './pages/CourierApplicationDetailPage'
export default function App() { return <Routes><Route element={<Navigate replace to="/dashboard" />} path="/" /><Route element={<LoginPage />} path="/login" /><Route element={<RegisterPage />} path="/register" /><Route element={<ForgotPasswordPage />} path="/forgot-password" /><Route element={<ResetPasswordPage />} path="/reset-password" /><Route element={<ProtectedRoute />}><Route element={<LogisticsLayout />}><Route element={<DashboardPage />} path="/dashboard" /><Route element={<PickupsPage />} path="/pickups" /><Route element={<PickupDetailPage />} path="/pickups/:pickupId" /><Route element={<CourierApplicationsPage />} path="/courier-applications" /><Route element={<CourierApplicationDetailPage />} path="/courier-applications/:affiliationId" /><Route element={<AccountPage />} path="/account" /><Route element={<PolicyConsentPage />} path="/policy-consent" /></Route></Route><Route element={<Navigate replace to="/dashboard" />} path="*" /></Routes> }
