const base = (import.meta.env.VITE_API_URL ?? '').replace(/\/$/, '')
type Payload = { code?: string; message?: string; errors?: Record<string, string[]> }
export class ApiError extends Error { constructor(readonly status: number, readonly payload: Payload) { super(payload.message ?? 'Something went wrong. Please try again.'); this.name = 'ApiError' } get code() { return this.payload.code }; get errors() { return this.payload.errors ?? {} } }
const url = (path: string) => `${base}${path}`
const token = () => document.cookie.split('; ').find((entry) => entry.startsWith('XSRF-TOKEN='))?.split('=').slice(1).join('=')
export async function csrf() { const response = await fetch(url('/sanctum/csrf-cookie'), { credentials: 'include', headers: { Accept: 'application/json' } }); if (!response.ok) throw new ApiError(response.status, { message: 'Unable to start a secure session.' }) }
export async function request<T>(path: string, options: RequestInit = {}): Promise<T> { const headers = new Headers(options.headers); headers.set('Accept', 'application/json'); if (options.body && !(options.body instanceof FormData)) headers.set('Content-Type', 'application/json'); const xsrf = token(); if (xsrf) headers.set('X-XSRF-TOKEN', decodeURIComponent(xsrf)); const response = await fetch(url(path), { ...options, credentials: 'include', headers }); const payload = await response.json().catch(() => ({})) as Payload & T; if (!response.ok) throw new ApiError(response.status, payload); return payload }
export async function requestWithTimeout<T>(path: string, options: RequestInit = {}, timeoutMs = 15000): Promise<T> { const controller = new AbortController(); const timer = window.setTimeout(() => controller.abort(), timeoutMs); try { return await request<T>(path, { ...options, signal: controller.signal }) } catch (caught) { if (controller.signal.aborted) throw new ApiError(408, { message: 'The request timed out. Check your connection and try again.' }); throw caught } finally { window.clearTimeout(timer) } }
export async function uploadForm<T>(path: string, body: FormData, onProgress?: (percent: number) => void): Promise<T> { await csrf(); return new Promise((resolve, reject) => { const xhr = new XMLHttpRequest(); xhr.open('POST', url(path)); xhr.withCredentials = true; xhr.setRequestHeader('Accept', 'application/json'); const xsrf = token(); if (xsrf) xhr.setRequestHeader('X-XSRF-TOKEN', decodeURIComponent(xsrf)); xhr.upload.addEventListener('progress', (event) => { if (event.lengthComputable) onProgress?.(Math.round((event.loaded / event.total) * 100)) }); xhr.addEventListener('load', () => { const payload = (() => { try { return JSON.parse(xhr.responseText) as Payload & T } catch { return {} as Payload & T } })(); if (xhr.status >= 200 && xhr.status < 300) { onProgress?.(100); resolve(payload) } else reject(new ApiError(xhr.status, payload)) }); xhr.addEventListener('error', () => reject(new ApiError(0, { message: 'We could not upload the image. Check your connection and try again.' }))); xhr.send(body) }) }
export async function blob(path: string, timeoutMs = 15000): Promise<Blob> { const controller = new AbortController(); const timer = window.setTimeout(() => controller.abort(), timeoutMs); try { const response = await fetch(url(path), { credentials: 'include', signal: controller.signal, headers: { Accept: 'image/jpeg,image/png,image/webp' } }); if (!response.ok) { const payload = await response.json().catch(() => ({})) as Payload; throw new ApiError(response.status, payload) } return await response.blob() } catch (caught) { if (controller.signal.aborted) throw new ApiError(408, { message: 'The evidence request timed out. Try again.' }); throw caught } finally { window.clearTimeout(timer) } }
export async function pdf(path: string): Promise<Blob> { const response = await fetch(url(path), { credentials: 'include', headers: { Accept: 'application/pdf' } }); if (!response.ok) { const payload = await response.json().catch(() => ({})) as Payload; throw new ApiError(response.status, payload) } return response.blob() }
export function authError(error: ApiError) { if (error.code === 'ACCOUNT_PENDING_APPROVAL') return 'Your Logistics registration is waiting for Admin approval.'; if (error.code === 'ACCOUNT_REJECTED') return 'Your Logistics registration was not approved.'; if (error.code === 'ACCOUNT_SUSPENDED') return 'This Logistics account is suspended.'; return error.errors.email?.[0] ?? error.message }
