export type Request = <T>(path: string, options?: RequestInit) => Promise<T>
export type PaymentRole = 'admin' | 'seller' | 'logistics'
export type PaymentProps = { role: PaymentRole; prefix: string; request: Request; url: (path: string) => string; canManage?: boolean; openInvoice?: (id: string) => void; openBatch?: (id: string) => void }
export type Invoice = { id: string; reference: string; order_id: string; order_reference: string; logistics_organization_id: string | null; collector_name: string | null; status: string; overdue: boolean; currency: string; total_cents: number; remaining_cents: number; delivered_at: string; due_at: string; seller_eligible_at: string; logistics_eligible_at: string; paid_at: string | null; review_reason: string | null }
export type Attempt = { id: string; status: string; direction: string; provider_reference: string | null; amount_cents: number; currency: string; failure_code: string | null; cod_remittance_batch_id: string | null; finance_payout_id: string | null; created_at: string; resolved_at: string | null }
export type Batch = { id: string; collector_name?: string | null; reference: string; status: string; currency: string; total_cents: number; is_gateway: boolean; submitted_at: string; cleared_at: string | null; rejection_reason: string | null; allocations: { order_id: string; order_reference: string; amount_cents: number }[]; attempts: Attempt[] }
export type Payout = { id: string; beneficiary_name?: string | null; beneficiary_type: string; beneficiary_id: string; status: string; currency: string; amount_cents: number; provider_reference: string | null; submitted_at: string; resolved_at: string | null; attempts: Attempt[]; is_sandbox: boolean }
export type Obligation = { order_id: string; order_reference: string; beneficiary_type: 'seller' | 'logistics'; beneficiary_id: string; beneficiary_name: string; currency: string; amount_cents: number; eligible_at: string; blocked: string[] }
export type Page<T> = { data: T[]; summary?: { currency: string; outstanding_cents: number; overdue_cents: number }; current_page?: number; last_page?: number; total?: number; meta?: { current_page: number; last_page: number; total: number } }
export type Settings = { cod_deadline_hours: number; seller_delay_hours: number; logistics_delay_hours: number; collection_time: string; seller_payout_time: string; logistics_payout_time: string; collection_enabled: boolean; seller_payout_enabled: boolean; logistics_payout_enabled: boolean }
export type SettingsResponse = { data: { platform: Settings; collection: Settings | null; timezone: string; next_collection_at: string | null; gateway_enabled: boolean; can_manage: boolean } }
export type GatewayAccount = { id: string; reference: string; balance_cents: number; scenario: string; is_active: boolean }
export type GatewayTransaction = { id: string; direction: string; status: string; amount_cents: number; currency: string; account_reference: string; failure_code: string | null; metadata: { attempt_id: string }; created_at: string }
export type GatewayEvent = { id: string; delivery_attempts: number; delivered_at: string | null; payload: { type: string; data: unknown } }
export type SandboxResponse = { accounts: GatewayAccount[]; transactions: Page<GatewayTransaction>; events: GatewayEvent[]; organizations: { id: string; business_name: string }[] }
