<?php

namespace Database\Seeders\PhilippinesLogistics;

/** Researched districts; coordinates are representative development pins, not surveyed premises. */
class RegionalHubCatalog
{
    public static function hubs(): array
    {
        return [
            [
                'slug' => 'ncr',
                'account' => 'luzon01',
                'region' => 'National Capital Region (NCR)',
                'province' => 'Metro Manila',
                'city' => 'City of Manila',
                'barangay' => 'Port Area',
                'postal_code' => '1018',
                'latitude' => 14.5896,
                'longitude' => 120.9692,
                'address_line_1' => 'Manila port district',
                'reference' => 'PPA South Harbor Port Area freight gateway',
                'source' => 'https://www.ppa.com.ph/ppa_contactus',
            ],
            [
                'slug' => 'car',
                'account' => 'luzon02',
                'region' => 'Cordillera Administrative Region (CAR)',
                'province' => 'Benguet',
                'city' => 'City of Baguio',
                'barangay' => 'Kagitingan',
                'postal_code' => '2600',
                'latitude' => 16.416,
                'longitude' => 120.5955,
                'address_line_1' => 'Magsaysay Avenue area',
                'reference' => 'LBC Baguio Center Mall branch area',
                'source' => 'https://www.lbcexpress.com/branches-philippines/BENGUET',
            ],
            [
                'slug' => 'region-1',
                'account' => 'luzon03',
                'region' => 'Region I (Ilocos Region)',
                'province' => 'La Union',
                'city' => 'City of San Fernando',
                'barangay' => 'Catbangen',
                'postal_code' => '2500',
                'latitude' => 16.605,
                'longitude' => 120.315,
                'address_line_1' => 'San Fernando commercial district',
                'reference' => 'LBC San Fernando La Union branch city',
                'source' => 'https://www.lbcexpress.com/us/branch-holiday-schedule',
            ],
            [
                'slug' => 'region-2',
                'account' => 'luzon04',
                'region' => 'Region II (Cagayan Valley)',
                'province' => 'Cagayan',
                'city' => 'Tuguegarao City',
                'barangay' => 'Carig',
                'postal_code' => '3500',
                'latitude' => 17.656,
                'longitude' => 121.752,
                'address_line_1' => 'Carig regional center area',
                'reference' => 'LBC Carig Regional Center branch area',
                'source' => 'https://www.lbcexpress.com/branches-philippines/CAGAYAN',
            ],
            [
                'slug' => 'region-3',
                'account' => 'luzon05',
                'region' => 'Region III (Central Luzon)',
                'province' => 'Pampanga',
                'city' => 'City of San Fernando',
                'barangay' => 'San Isidro',
                'postal_code' => '2000',
                'latitude' => 15.05,
                'longitude' => 120.689,
                'address_line_1' => 'San Fernando freight corridor',
                'reference' => 'LBC Pampanga distribution operations',
                'source' => 'https://www.lbcexpressholdings.com/files/2020/11/23/1269/LBC_2019_Annual_Report.pdf',
            ],
            [
                'slug' => 'region-4a',
                'account' => 'luzon06',
                'region' => 'Region IV-A (CALABARZON)',
                'province' => 'Laguna',
                'city' => 'City of Calamba',
                'barangay' => 'Paciano Rizal',
                'postal_code' => '4027',
                'latitude' => 14.2117,
                'longitude' => 121.1653,
                'address_line_1' => 'Calamba industrial corridor',
                'reference' => 'RLX Calamba SPX warehouse complexes',
                'source' => 'https://rlxlogistics.ph/',
            ],
            [
                'slug' => 'region-4b',
                'account' => 'luzon07',
                'region' => 'MIMAROPA Region',
                'province' => 'Oriental Mindoro',
                'city' => 'City of Calapan',
                'barangay' => 'Tawiran',
                'postal_code' => '5200',
                'latitude' => 13.4117,
                'longitude' => 121.1803,
                'address_line_1' => 'Calapan road and port gateway',
                'reference' => 'PPA Calapan / Batangas RoRo gateway',
                'source' => 'https://starliteferries.com/',
            ],
            [
                'slug' => 'region-5',
                'account' => 'luzon08',
                'region' => 'Region V (Bicol Region)',
                'province' => 'Albay',
                'city' => 'City of Legazpi',
                'barangay' => 'Bgy. 36 - Kapantawan',
                'postal_code' => '4500',
                'latitude' => 13.146,
                'longitude' => 123.752,
                'address_line_1' => 'Legazpi commercial freight district',
                'reference' => 'LBC Legazpi branches',
                'source' => 'https://www.lbcexpress.com/branches-philippines/ALBAY',
            ],
            [
                'slug' => 'region-6',
                'account' => 'region-6',
                'region' => 'Region VI (Western Visayas)',
                'province' => 'Iloilo',
                'city' => 'City of Iloilo',
                'barangay' => 'Obrero-Lapuz',
                'postal_code' => '5000',
                'latitude' => 10.711,
                'longitude' => 122.582,
                'address_line_1' => 'Lapuz freight district',
                'reference' => 'FAST Iloilo Lapuz logistics office',
                'source' => 'https://fast.com.ph/contact-us/',
            ],
            [
                'slug' => 'nir',
                'account' => 'nir',
                'region' => 'Negros Island Region (NIR)',
                'province' => 'Negros Occidental',
                'city' => 'City of Bacolod',
                'barangay' => 'Singcang-Airport',
                'postal_code' => '6100',
                'latitude' => 10.647,
                'longitude' => 122.934,
                'address_line_1' => 'Magsaysay Avenue area',
                'reference' => 'FAST Bacolod Singcang logistics office',
                'source' => 'https://fast.com.ph/contact-us/',
            ],
            [
                'slug' => 'region-7',
                'account' => 'region-7',
                'region' => 'Region VII (Central Visayas)',
                'province' => 'Cebu',
                'city' => 'City of Mandaue',
                'barangay' => 'Subangdaku',
                'postal_code' => '6014',
                'latitude' => 10.323,
                'longitude' => 123.933,
                'address_line_1' => 'Mandaue highway freight corridor',
                'reference' => 'FAST Mandaue logistics headquarters',
                'source' => 'https://fast.com.ph/contact-us/',
            ],
            [
                'slug' => 'region-8',
                'account' => 'region-8',
                'region' => 'Region VIII (Eastern Visayas)',
                'province' => 'Leyte',
                'city' => 'City of Tacloban',
                'barangay' => 'Barangay 77',
                'postal_code' => '6500',
                'latitude' => 11.215,
                'longitude' => 125.01,
                'address_line_1' => 'Marasbaras freight district',
                'reference' => 'FAST Tacloban Barangay 77 office',
                'source' => 'https://fast.com.ph/contact-us/',
            ],
            [
                'slug' => 'region-9',
                'account' => 'region-9',
                'region' => 'Region IX (Zamboanga Peninsula)',
                'province' => 'Zamboanga del Sur',
                'city' => 'City of Zamboanga',
                'barangay' => 'Baliwasan',
                'postal_code' => '7000',
                'latitude' => 6.913,
                'longitude' => 122.061,
                'address_line_1' => 'Zamboanga urban freight corridor',
                'reference' => 'FAST Zamboanga distribution city',
                'source' => 'https://blog.fast.com.ph/warehousing-solutions-in-the-philippines-explained-a-complete-business-guide/',
            ],
            [
                'slug' => 'region-10',
                'account' => 'region-10',
                'region' => 'Region X (Northern Mindanao)',
                'province' => 'Misamis Oriental',
                'city' => 'City of Cagayan De Oro',
                'barangay' => 'Bulua',
                'postal_code' => '9000',
                'latitude' => 8.499,
                'longitude' => 124.622,
                'address_line_1' => 'Bulua Highway area',
                'reference' => 'FAST Cagayan de Oro Bulua office',
                'source' => 'https://fast.com.ph/contact-us/',
            ],
            [
                'slug' => 'region-11',
                'account' => 'region-11',
                'region' => 'Region XI (Davao Region)',
                'province' => 'Davao del Sur',
                'city' => 'City of Davao',
                'barangay' => 'Sasa',
                'postal_code' => '8000',
                'latitude' => 7.113,
                'longitude' => 125.65,
                'address_line_1' => 'Sasa freight district',
                'reference' => 'FAST Davao Sasa logistics office',
                'source' => 'https://fast.com.ph/contact-us/',
            ],
            [
                'slug' => 'region-12',
                'account' => 'region-12',
                'region' => 'Region XII (SOCCSKSARGEN)',
                'province' => 'South Cotabato',
                'city' => 'City of General Santos',
                'barangay' => 'Labangal',
                'postal_code' => '9500',
                'latitude' => 6.114,
                'longitude' => 125.155,
                'address_line_1' => 'Labangal Macar port corridor',
                'reference' => 'FAST General Santos Labangal office',
                'source' => 'https://fast.com.ph/contact-us/',
            ],
            [
                'slug' => 'region-13',
                'account' => 'region-13',
                'region' => 'Region XIII (Caraga)',
                'province' => 'Agusan del Norte',
                'city' => 'City of Butuan',
                'barangay' => 'Bayanihan Pob.',
                'postal_code' => '8600',
                'latitude' => 8.947,
                'longitude' => 125.52,
                'address_line_1' => 'Jose C. Aquino Avenue area',
                'reference' => 'FAST Butuan logistics office corridor',
                'source' => 'https://fast.com.ph/contact-us/',
            ],
            [
                'slug' => 'barmm',
                'account' => 'barmm',
                'region' => 'Bangsamoro Autonomous Region In Muslim Mindanao (BARMM)',
                'province' => 'Maguindanao del Norte',
                'city' => 'Sultan Kudarat',
                'barangay' => 'Salimbao',
                'postal_code' => '9605',
                'latitude' => 7.263,
                'longitude' => 124.257,
                'address_line_1' => 'Salimbao National Highway area',
                'reference' => 'FAST Cotabato-area office in Sultan Kudarat',
                'source' => 'https://fast.com.ph/contact-us/',
            ],
        ];
    }
}
